import React from "react"
import Navbar from "../Navbar"
import Footer from "../Footer"
import Head from "next/head"
import styles from "./layout.module.css"

const index = ({ children }) => {
	return (
		<>
			<Head>
				<title>E-Commerce</title>
				<link rel="icon" href="/favicon.ico" />
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0"
				></meta>
			</Head>

			<Navbar />
			<main>{children}</main>
			<Footer />
		</>
	)
}

export default index
